on: push
name: Mirror to GitLab
jobs:
  pushToGitLab:
    name: Push to GitLab
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Push to GitLab
      uses: <YOU_NAME_GITLAB>/<YOU_NAME_REPO_GIT_LAB>@master
      env:
        GIT_USERNAME: ${{ secrets.GIT_USER }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      with:
        args: ${{ secrets.GIT_GITLAB_URL_REPO }}